version: '3'
services:
  web:
    build: 
      context: ./web
    ports:
     - "5000:5000"
    links:
      - hypernova
    environment:
      - APP__HYPERNOVAENDPOINT=http://hypernova:3000
  hypernova:
    build: 
      context: ./hypernova
    ports:
     - "3000:3000"